# Generated by Django 6.0.1 on 2026-01-31 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('idempotency_key', 'delivery_date', 'created_by')},
        ),
    ]
