# Generated by Django 6.0.1 on 2026-01-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_delivery_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
